# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='text',
        ),
        migrations.AddField(
            model_name='listitem',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
