# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default='my-first-to-do-list'),
            preserve_default=False,
        ),
    ]
