# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20171214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
