# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_listitem_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
